
DROP DATABASE IF EXISTS ByteBaazar;

CREATE DATABASE ByteBaazar;

USE ByteBaazar;

CREATE TABLE CLIENTES (
    CLI_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_CPF VARCHAR(15) NOT NULL,
    CLI_DATA_NASCIMENTO DATE NOT NULL,
    CLI_EMAIL VARCHAR(50) NOT NULL,
    CLI_SENHA VARCHAR(100) NOT NULL,
    CLI_GENERO VARCHAR(10) NOT NULL,
    CLI_TELEFONE VARCHAR(20) NOT NULL
);

CREATE TABLE PRODUTOS (
    PRD_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRD_NOME VARCHAR(100) NOT NULL,
    PRD_DESCRICAO VARCHAR(255) NOT NULL,
    PRD_PRECO DECIMAL(10, 2) NOT NULL,
    PRD_QUANTIDADE INT NOT NULL,
    PRD_CATEGORIA INT NOT NULL,
    PRD_IMAGEM VARCHAR(255)
);

CREATE TABLE ESTOQUE (
    EST_ID INT AUTO_INCREMENT PRIMARY KEY,
    EST_PRODUTO_ID INT,
    EST_QUANTIDADE INT NOT NULL,
    FOREIGN KEY (EST_PRODUTO_ID) REFERENCES PRODUTOS(PRD_ID)
);

CREATE TABLE VENDAS (
    VND_ID INT AUTO_INCREMENT PRIMARY KEY,
    VND_CLIENTE_ID INT,
    VND_DATA_VENDA DATE NOT NULL,
    VND_VALOR_TOTAL DECIMAL(10, 2) NOT NULL,
    VND_STATUS VARCHAR(50) NOT NULL,
    FOREIGN KEY (VND_CLIENTE_ID) REFERENCES CLIENTES(CLI_ID)
);

CREATE TABLE ProdutosVenda (
    PRDVND_ID INT AUTO_INCREMENT PRIMARY KEY,
    fk_VENDAS_VND_ID INT,
    fk_PRODUTOS_PRD_ID INT,
    PRDVND_QUANTIDADE INT NOT NULL,
    PRDVND_VALOR_UNITARIO DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (fk_VENDAS_VND_ID) REFERENCES VENDAS(VND_ID),
    FOREIGN KEY (fk_PRODUTOS_PRD_ID) REFERENCES PRODUTOS(PRD_ID)
);

CREATE TABLE OFERTAS (
    OFR_ID INT AUTO_INCREMENT PRIMARY KEY,
    OFR_PRODUTO_ID INT,
    OFR_DESCONTO DECIMAL(5, 2) NOT NULL,
    OFR_DATA_INICIO DATE NOT NULL,
    OFR_DATA_FIM DATE NOT NULL,
    FOREIGN KEY (OFR_PRODUTO_ID) REFERENCES PRODUTOS(PRD_ID)
);
